<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panel de Administración</title>
</head>
<body>
    <h1>Panel de Administración</h1>
    
    <?php
        echo '<form action="index.php" name="nPanel" method="POST">
        <input type="submit" name="editar" value="Editar Publicación" placeholder="Editar">
        <input type="submit" name="cambiar" value="Cambiar Rol" placeholder="Cambiar Rol">
        </form>';

    ?>
</body>
</html>