<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Publicaciones</title>
</head>
<body>
    <h1>Editar Publicaciones</h1>

    <?php
        foreach($pubs as $pub) { 
            echo '<img src="public/img/' . $pub->getImage() . '" width="200px"/><br>'; 
            // echo $pub->getTitle() . "<br><br>";
            // echo $pub->getText() . "<br><br>";

            // Mostrar formulario de edición con los datos actuales de la publicación
            echo '<form action="index.php?c=adminPanel&editPub=1" method="POST" enctype="multipart/form-data">
                Título: <input type="text" name="editedTitle" value="' . $pub->getTitle() . '" required/><br><br>
                Texto: <textarea name="editedText" required>' . $pub->getText() . '</textarea><br><br>
                <input type="hidden" name="pubId" value="' . $pub->getId() . '">
                <input type="submit" name="pubEdit" value="Editar">
            </form>';
            echo '<br>';
            echo '<hr>';
        }
    ?>

</body>
</html>