<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Publicaciones</h1>

    <?php


    if(!empty($_SESSION['user'])){
        if($_SESSION['user']->getRol()>1) {
            echo "<a href='index.php?c=pub&newPub=1'>Añadir publicación</a>";
            echo "<br><br>";
            echo "<a href='index.php?c=adminPanel&nPanel=1'>Panel Administración</a>";
            echo "<br><br>";    
        }
        echo "<a href= 'index.php?c=user&logout=1'>Logout</a><br><br>";
    } 
    else {
        echo '<br><br>';
        echo '<form method="POST" action="index.php?c=user">
        Nombre: <input type="text" name="username" placeholder="Nombre" required/><br>
        Contraseña: <input type="password" name="password" placeholder="Contraseña" required/><br>
        <input type="submit" name="login" value="Entrar" placeholder="Entrar">
        </form>';
        echo '<br><br>';
        echo '<hr>';
    }
  

    foreach($pubs as $pub){  
        echo '<img src="public/img/' .$pub->getImage().'" width="200px"/>';      
        echo $pub->getTitle()."<br><br>";
        echo $pub->getText()."<br>";

        foreach($pub->getComments() as $comment) {
            echo $comment->getUser_id()->getUsername()." ha dicho: ".$comment->getComment();
            echo '<br>';
        }

        echo '<form method="POST" action="index.php?c=comment">
            <textarea name="comment" rows="5" cols="40" placeholder="Escribe comentario"></textarea><br>
            <input type="hidden" name="pub_id" value="'.$pub->getId().'">
            <input type="submit" name="newComment" value="Publicar">
            </form>';
        echo '<br>';
        echo '<hr>';

    }

    ?>


</body>
</html>




