<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Publicaciones</h1>

    <?php

    if(!empty($_SESSION['user']) && $_SESSION['user']->getRol()>1) {
        echo "<a href='index.php?newPub=1'>Añadir publicación</a> <br>";
        
    } else{
        echo "El usuario no existe";
        echo "<br><br>";
    }
    

    foreach($pubs as $pub){  
        echo '<img src="public/img/' .$pub->getImage().'" width="100px"/>';      
        echo $pub->getTitle()."<br><br>";
        echo $pub->getText()."<br>";
    }

    ?>

    <br><br>
    <form method="POST" action="index.php">
            Nombre: <input type="text" name="username" placeholder="Nombre" required/><br>
            Contraseña: <input type="password" name="password" placeholder="Contraseña" required/><br>
            <input type="submit" name="login" value="Entrar" placeholder="Entrar">
    </form>

</body>
</html>




