<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevas Publicaciones</title>
</head>
<body>
    <h1>Añadir Publicaciones</h1>

    <!-- enctype es obligatorio cuando estamos enviando archivos -->
    <form action="index.php" method="POST" enctype="multipart/form-data" > 
            Título: <input type="text" name="title" placeholder="Título" required/><br>
            Texto: <textarea name="text" required></textarea><br>
            <input type="file" name="img">
            <input type="submit" name="newPub" value="Añadir" placeholder="Añadir">
    </form>
</body>
</html>