<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nuevas Publicaciones</title>
</head>
<body>
    <h1>Añadir Publicaciones</h1>

    <form method="POST" action="index.php">
            Título: <input type="text" name="title" placeholder="Título" required/><br>
            Texto: <input type="text" name="text" placeholder="Texto" required/><br>
            <input type="submit" name="newPub" value="Añadir" placeholder="Añadir">
    </form>
</body>
</html>