<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buscar Publicación</title>
</head>
<body>
    <h1>Buscar Publicación</h1>
    <form action="index.php?c=search" method="POST">
        Buscar: <input type="text" name="searchPub" placeholder="Buscar" required/><br>
        <input type="submit" value="Buscar">
    </form>
</body>
</html>
