<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>

    <style>
        a {
            text-decoration: none;
            background-color: blue;
            color: white;
            border-radius: 10px;
            box-shadow: 0px 10px 10px 0px lightblue;
            margin: 10px;
            padding: 5px;
        }
    </style>

</head>
<body>
    <h1>Bienvenido Admin!</h1>
    <a href="index.php?c=pc&action=productView">Control de Productos</a>
    <a href='index.php?c=ac&editRol=1'>Ver Usuarios</a>
    <a href="index.php?c=login&logout=1">Logout</a>
</body>
</html>
