<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    
</head>

<body>
    <?php
    if (!empty($_POST['registrarse'])) {
        echo "<h1>Registrarse</h1>";
    } else {
        echo "<h1>Login</h1>";
    }
    ?>
    <form action="index.php?c=login" method="POST">
        <label for="username">Username</label>
        <input type="text" name="name">
        <br><br>
        <?php
        if (!empty($_POST['registrarse'])) {
            echo '<label for="password">Password </label>';
            echo '<input type="password" name="password">';
            echo '<br><br>';
            echo '<label for="password2">Confirmar password </label>';
            echo '<input type="password" name="password2">';
        } else {
            echo '<label for="password">Password </label>';
            echo '<input type="password" name="password">';
        }
        ?>
        <br><br>
        <?php
        if (!empty($_POST['registrarse'])) {
            echo '<input type="submit" value="Enviar" name="login2">';
        } else {
            echo '<input type="submit" value="Enviar" name="login">';
        }
        ?>
        <br>
        <br>
        <br>
        <?php
        if (empty($_POST['registrarse'])) {
            echo '<input type="submit" name="registrarse" value="Registrarse">';
        }
        ?>
        <?php
        if (!empty($_POST['registrarse'])) {
            echo '<input type="submit" name="login" value="Volver al login">';
            echo "<br><br><br>";
        }
        ?>
    </form>
</body>

</html>