<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form method="POST" action="index.php?c=login">
            Nombre: <input type="text" name="name" placeholder="Nombre" required/><br>
            Contraseña: <input type="password" name="password" placeholder="Contraseña" required/><br>
            <input type="submit" name="login" value="Entrar" placeholder="Entrar">
    </form>

</body>
</html>