<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shop</title>

    <style>
        a {
            margin-left: 20px;
            text-decoration: none;
        }
    </style>

</head>
<body>
    <h1>Welcome to MyShop</h1>

    <?php
        if(empty($_SESSION['user'])) {
            echo '<a href="index.php?c=user&login=1">Login</a>';
            echo '<a href="index.php?c=user&login=1">Sign Up</a>';
        }
    ?>

    
</body>
</html>