<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Panel de Administración</title>
</head>
<body>
    <h1>Panel de Administración</h1>
    
    <?php
        echo "<a href='index.php?c=adminPanel&editPub=1'>Editar Publicación</a>";
        echo "<br><br>";
        echo "<a href='index.php?c=adminPanel&editRol=1'>Cambiar Rol</a>";
        echo "<br><br>";
    ?>
</body>
</html>