<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cambiar Rol</title>
</head>
<body>
    <h1>Cambiar Rol</h1>
    <?php
    foreach($users as $user) {
        echo $user->getUserName()."<br>";
    
        echo '
        <form method="POST" action="index.php?c=adminPanel">
        <select name="state">';
            foreach($state as $k => $v){
                echo '<option value="' .$k.'"';
                    if($user->getRol()==$k) echo "SELECTED";
                echo '>' .$v. '</option>';
            }
        echo '</select>
        <input type="hidden" name="id_user" value="'.$user->getId().'">
        <input type="submit" name="changeRol" value="Cambiar Rol">
        </form>
        ';
    }
        
    ?>
</body>
</html>