
<html>

<head>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>gestion tickets</h1>

        <a href="index.php?c=admin&users">Administrar usuarios</a>

        <?php

        //mostrar tickets


        foreach($tickets as $t){
            echo '<h3>'.$t->getTitle().'</h3>'.$t->getText()."<br>";
        }

        ?>
    </div>


</body>
</html>