<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>

    <style>
        a {
            text-decoration: none;
            background-color: blue;
            color: white;
            border-radius: 10px;
            box-shadow: 0px 10px 10px 0px lightblue;
            margin: 10px;
            padding: 5px;
        }
    </style>
    
</head>

<body>
<h1>Bienvenido Admin!</h1>
    <div class="enlaces">
        <a href="index.php?c=pc&ticketView=1">Ver Tickets</a>
        <a href='index.php?c=admin&editRol=1'>Ver Usuarios</a>
        <a href="index.php?c=login&logout=1">Logout</a>
    </div>
    
</body>

</html>
