
<html>

<head>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Gestión Tickets</h1>

        <a href="index.php?c=admin&users">Administrar usuarios</a>

        <?php

        //mostrar tickets


        foreach($tickets as $t){
            echo '<h3>Título: '.$t->getTitle().'</h3>Texto: '.$t->getText()."<br>";
        }
        
        ?>
        <br>
        <a href="index.php?c=user&logout">Salir</a>
    </div>


</body>
</html>