
<html>

<head>

</head>
<body>
    <div class="container">
        <h1>gestion tickets</h1>

        registrate:

        <form action="index.php?c=user" method="POST">
            Nombre: <input type="text" name="username"><br>
            Contraseña: <input type="password" name="password"><br>
            Repite tu contraseña: <input type="password" name="password2"><br>
            <input type="submit" name="register" value="entrar">
        </form>
    </div>



</body>
</html>