
<html>

<head>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>Gestión de Tickets</h1>

        <p>Regístrate:</p>

        <form action="index.php?c=user" method="POST">
            Nombre: <input type="text" name="username"><br>
            Contraseña: <input type="password" name="password"><br>
            Repite tu contraseña: <input type="password" name="password2"><br>
            <input type="submit" name="register" value="Entrar">
        </form>
    </div>



</body>
</html>