<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cliente Dashboard</title>

    <!-- <link rel="stylesheet" href="/fpDaw2/entornoServidor/Tickets/styles.css"> -->

</head>

<body>
    <div class="container">
        <h1>Welcome <?php echo $_SESSION['user']->getUsername(); ?>!</h1>
        <h2>Crear nuevo ticket</h2>
        <form action="index.php?c=user" method="POST">
            <label for="title">Título del ticket</label>
            <input type="text" name="title" required>
            <br><br>        
            <label for="text">Texto del ticket</label>
            <textarea name="text" rows="4" required></textarea>
            <br><br>

            <input type="submit" value="Enviar ticket" name="createTicket">
        </form>
    </div>
    

</body>

</html>
