<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <?php
    // Verificar si el usuario está autenticado
    if (isset($_SESSION['user'])) {
        $user = $_SESSION['user'];
        echo "<h1>Bienvenido, " . $user->getUserName() . " a AroniFy</h1>";
        echo "<a href='index.php?c=user&action=logout'>Cerrar Sesión</a>";
        // Mostrar aquí las listas de reproducción del usuario
        // Agregar formulario de búsqueda de canciones
    } else {
        // Mostrar mensaje de bienvenida y enlaces de inicio de sesión y registro
        echo "<h1>Bienvenido a AroniFy</h1>";
        echo "<a href='index.php?c=user&action=login'>Iniciar Sesión</a>";
        echo "<br><br>";
        echo "<a href='index.php?c=user&action=register'>Registrarse</a>";
    }
    ?>


</body>
</html>

