<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <a href="index.php?c=login&logout=1">Logout</a>
    <h1>Bienvenido a Aronify,  <?php echo $_SESSION['user']->getUsername(); ?></h1>

    <h3>Tus listas creadas</h3>
    <?php
    foreach ($listas as $lista) {
        echo $lista->getName() . " <a href='index.php?c=pl&editar=" . $lista->getId() . "&pl=" . $lista->getName() . "'>Editar playlist</a><br>";
    }
    ?>

    <h3>Tus listas favoritas</h3>

    <?php
    $listasFavoritas = $_SESSION['user']->getListasFavs();
    foreach ($listasFavoritas as $lista) {
        echo $lista->getName() . " <a href='index.php?c=pl&abrir=" . $lista->getId() . "'>Abrir playlist</a><br>";
    }
    ?>


    <h3>Añadir cancion</h3>
    <form action="index.php?c=cancion" method="POST" enctype="multipart/form-data">
        <label for="titulo">Titulo</label>
        <input type="text" name="titulo"><br><br>
        <label for="autor">Autor</label>
        <input type="text" name="autor"><br><br>
        <label for="duracion">Duracion</label>
        <input type="text" name="duracion"><br><br>
        <label for="img">Imagen</label>
        <input type="file" name="img"><br><br>
        <label for="mp3">Cancion</label>
        <input type="file" name="mp3"><br><br>
        <input type="submit" name="cancion" value="Enviar cancion"><br><br>
    </form>

    <h3>Añadir playlist</h3>
    <form action="index.php?c=pl" method="POST">
        <label for="tituloPL">Titulo</label>
        <input type="text" name="tituloPL"><br><br>
        <input type="submit" name="pl" value="Enviar playlist"><br><br>
    </form>

    <h3>Buscar playlist de usuarios</h3>

    <form action="index.php?c=pl" method="POST">
        <input type="text" name="buscador" placeholder="Buscar...">
        <input type="submit" value="Buscar" name="buscarBuscador">
    </form>

    <?php
    if (isset($listasBuscador)) {
        foreach ($listasBuscador as $lista) {
            echo "<br>" . $lista->getName() . "<a href='index.php?c=pl&fav=" . $lista->getId() . "'> Favorito</a>";
        }
    }


    ?>
</body>


</html>