<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registrarse en AroniFy</title>
</head>
<body>
    <h1>Registrarse en AroniFy</h1>

    <form action="index.php?c=user&action=register" method="post">
        <label for="username">Nombre de Usuario:</label>
        <input type="text" id="username" name="username" required>

        <label for="password">Contraseña:</label>
        <input type="password" id="password" name="password" required>

        <label for="confirm_password">Confirmar Contraseña:</label>
        <input type="password" id="confirm_password" name="confirm_password" required>

        <button type="submit">Registrarse</button>
        
    </form>

    <p>¿Ya tienes una cuenta? <a href="index.php?c=user&action=login">Iniciar Sesión</a></p>
</body>
</html>
